[package]
name = "rust-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
bcrypt = "0.18.0"
dotenvy = "0.15.7"
jsonwebtoken = "10.3.0"
serde = "1.0.228"
serde_json = "1.0.149"
sqlx = "0.8.6"
sqlx-cli = "0.8.6"
tokio = "1.49.0"
